version: '3.7'

services:
  library-web:
    image: node:12-alpine
    container_name: library-web
    volumes:
      - .:/app:ro
      - /app/node_modules
    working_dir: /app
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=${EXTERNAL_NETWORK:-ridi}'
      - 'traefik.frontend.rule=Host:library.local.ridi.io'
    networks:
      - traefik
    ports:
      - 3000
    init: true
    entrypoint: /app/docker/run-dev.sh
